"""empty message

Revision ID: 062b4fefe827
Revises: a60b895b2f51
Create Date: 2024-05-29 01:48:56.733478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '062b4fefe827'
down_revision = 'a60b895b2f51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('administration', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img', sa.Text(), nullable=True))

    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img', sa.Text(), nullable=True))

    with op.batch_alter_table('workers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workers', schema=None) as batch_op:
        batch_op.drop_column('img')

    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.drop_column('img')

    with op.batch_alter_table('administration', schema=None) as batch_op:
        batch_op.drop_column('img')

    # ### end Alembic commands ###
