"""empty message

Revision ID: 3cedb8f9015c
Revises: 94f3cd5d1ad7
Create Date: 2024-06-25 16:21:22.224217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cedb8f9015c'
down_revision = '94f3cd5d1ad7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_constraint('fk_question_fk_question_theme_themes', type_='foreignkey')
        batch_op.drop_column('fk_question_theme')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fk_question_theme', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key('fk_question_fk_question_theme_themes', 'themes', ['fk_question_theme'], ['id'])

    # ### end Alembic commands ###
