"""empty message

Revision ID: 42b18d2d9b0f
Revises: 062b4fefe827
Create Date: 2024-05-30 02:36:26.879330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42b18d2d9b0f'
down_revision = '062b4fefe827'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('administration', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_start_work', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('inst', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('telegram', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('vk', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('tiktok', sa.String(length=255), nullable=True))

    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_start_work', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('inst', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('telegram', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('vk', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('tiktok', sa.String(length=255), nullable=True))

    with op.batch_alter_table('workers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_start_work', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('inst', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('telegram', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('vk', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('tiktok', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workers', schema=None) as batch_op:
        batch_op.drop_column('tiktok')
        batch_op.drop_column('vk')
        batch_op.drop_column('telegram')
        batch_op.drop_column('inst')
        batch_op.drop_column('data_start_work')

    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.drop_column('tiktok')
        batch_op.drop_column('vk')
        batch_op.drop_column('telegram')
        batch_op.drop_column('inst')
        batch_op.drop_column('data_start_work')

    with op.batch_alter_table('administration', schema=None) as batch_op:
        batch_op.drop_column('tiktok')
        batch_op.drop_column('vk')
        batch_op.drop_column('telegram')
        batch_op.drop_column('inst')
        batch_op.drop_column('data_start_work')

    # ### end Alembic commands ###
