"""empty message

Revision ID: 46ca195a3bbf
Revises: 70fc5dc6eca0
Create Date: 2024-06-25 21:27:43.555277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46ca195a3bbf'
down_revision = '70fc5dc6eca0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max', sa.Integer(), nullable=False))
        batch_op.alter_column('result',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('result', schema=None) as batch_op:
        batch_op.alter_column('result',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.drop_column('max')

    # ### end Alembic commands ###
