"""empty message

Revision ID: 70fc5dc6eca0
Revises: 3cedb8f9015c
Create Date: 2024-06-25 21:15:27.997455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70fc5dc6eca0'
down_revision = '3cedb8f9015c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('result', schema=None) as batch_op:
        batch_op.drop_column('code')

    # ### end Alembic commands ###
