"""empty message

Revision ID: 94f3cd5d1ad7
Revises: 
Create Date: 2024-06-25 16:10:42.928692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94f3cd5d1ad7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fk_question_theme', sa.Integer(), nullable=False))
        batch_op.drop_constraint('fk_question_theme_id_themes', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_question_fk_question_theme_themes'), 'themes', ['fk_question_theme'], ['id'])
        batch_op.drop_column('theme_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('theme_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_question_fk_question_theme_themes'), type_='foreignkey')
        batch_op.create_foreign_key('fk_question_theme_id_themes', 'themes', ['theme_id'], ['id'])
        batch_op.drop_column('fk_question_theme')

    # ### end Alembic commands ###
